name: Build and Deploy
on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          persist-credentials: false

      - name: Install and Build
        uses: actions/setup-node@v1
      - run: npm install
      - run: npm run build
      - run: npm run export
        env:
          CI: true
          DEPLOY_TARGET: edu.fortress-arena
      - run: touch out/.nojekyll

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          GITHUB_TOKEN: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          BRANCH: edu.fortress-arena
          FOLDER: ./out
          CLEAN: true
